services:
  sirama_poa_init:
    image: "etclabscore/core-geth:version-1.12.14"
    container_name: "sirama_poa_init"
    command: "--datadir-=/root/.ethereum init /app/genesis.json"
    volumes:
      - ./poa/data:/root/.ethereum
      - ./poa/genesis.json:/app/genesis.json
    
  sirama_poa_nodes:
    image: "etclabscore/core-geth:version-1.12.14"
    container_name: "sirama_poa_nodes"
    restart: on-failure
    command:
      - datadir=/root/.ethereum
      - --http
      - --http.api=eth,net,web3
      - --http.corsdomain=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --ws
      - --ws.api=eth,net,web3
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/app/jwtsecret
      - --networkid=1131976
      - --syncmode=full
      - --gcmode "archive" \
      - --port=30303
      - --allow-insecure-unlock 
      - --unlock $(cat /app/account)
      - --password /app/password
      - --mine
      - --miner.etherbase $(cat /app/account)
    ports:
      - 38545:8545
      - 38546:8546
      - 43303:30303/tcp
      - 43303:30303/tcp
    volumes:
      - ./poa/data:/root/.ethereum
      - ./poa/jwtsecret:/app/jwtsecret
      - ./poa/account:/app/account.txt
      - ./poa/password:/app/password.txt
    depends_on:
      - sirama_poa_init:
          condition: service_completed_successfully
  


  # sirama-poa-nodes:
  #   image: sirama-poa:1.0
  #   container_name: sirama-poa
  #   restart: always
  #   entrypoint: "/app/chain"
  #   ports:
  #     - 38545:8545
  #     - 38546:8546
  #   volumes:
  #     - sirama-poa-data:/app/chain-data/geth
  #     - ./credentials:/app/credentials
  #     - ./credentials/keystore:/app/chain-data/keystore
  #   depends_on:
  #     sirama-poa-genesis:
  #       condition: service_completed_successfully

  # sirama-poa-genesis:
  #   image: sirama-poa:1.0
  #   container_name: sirama-poa-genesis
  #   entrypoint: "/app/genesis"
  #   volumes:
  #     - sirama-poa-data:/app/chain-data/geth

# volumes:
#   sirama-poa-data:
# admin.addPeer("enode://243620512d0bb93aada80cbba2b332cfd8e0d11b0750d03f3a6ee8d15658cfbac48841940a6bac3420ac789716b1c3d41f6b58cc9256a00ccd2b08508c5dd1f4@162.243.184.91:30304")
# admin.addPeer("enode://460880db0cb57a71635c3c8cdd83c8b976effcc5e58efa1d6a69d7404c1e44191a0b67c5ce1d0ff9423e19795664ee21e8010228b1ca3f05b9d5a6f054a23b9b@165.227.186.19:30304")
# admin.addPeer("enode://1986c16f54b016c123379764ac6d2f1fb5de216a95f90b250ef872677ece144eff3beae4891033ce068edfbd34caf0c5f5db02ec9275c773b00f78583a700642@167.172.232.135:30304")
# admin.addPeer("enode://736b18314d691058084be596a708a2029a7a10012c016f31d7d98f8d694b2c06f5bde4bcad9a8d32ca4fc361458633e70d918981242cf13037694491c40b9283@165.232.134.178:30304")
# admin.addPeer("enode://73c1f81ab9227ba273c68034e6bc942036f893939751e845e8c3e4eec232b9384b361e29c30a9ac27a314d97357494542e70cbbf30ed189525bcdaee7628332e@143.198.12.250:30304")

# clique.propose("0xf97404a7ee283ee1e4c03874958e11e29dcf4937", true)
# clique.propose("0xab501515e47315e7759f0dfe3dfe313e3af8dbf3", true)
# clique.propose("0xeeed36312ee77c085692422632b12b03c26b26d6", true)
# clique.propose("0x3f26a748468838c318aa7982e760b253e3cc4544", true)


# web3.eth.sendTransaction({
#     from: "0x83ee27632e313034703594da93b52a5405fe9276",
#     to: "0x01FEdeD5655D14873f81Be2493cfd09bC3D55D7A",
#     value: web3.toWei(1, "ether")
# })

# normal image bread weather absent original fog rice angry element walnut reduce life limit prepare stay benefit chase aware lonely stool bachelor danger suit